# Configuration documentation:
# https://docs.getnao.io/nao-agent/context-builder/configuration#nao_config-yaml

project_name: pulscheck-analytics
databases:
- type: duckdb
  name: duckdb-demo
  include:
  - main.customers
  - main.subscriptions
  - main.invoices
  - main.response_packages
  - main.surveys
  - main.survey_responses
  exclude: []
  templates:
  - columns
  - preview
  - profiling
  - ai_summary
  profiling:
    refresh_policy: always
    interval_days: 7
  path: ./pulscheck.duckdb
repos: []
llm:
  provider: anthropic
  api_key: REDACTED
  annotation_model: claude-3-7-sonnet-latest
